/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AtendimentosController;
import controller.FuncionariosController;
import controller.ServicosController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.AtendimentoProd;
import model.AtendimentoServ;
import model.Atendimentos;
import model.Servicos;

/**
 *
 * @author suezin
 */
public class FrCadAtendimento extends javax.swing.JDialog {

    private int idCliente;
    private int idAnimal;
    private int idServico;
    private int idProduto;
    private String precoServ;
    private String precoProd;
    private String tempo;

    /**
     * Creates new form FrCadAtendimento
     */
    public FrCadAtendimento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAnimal = new javax.swing.JTextField();
        btnBuscarAnimal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtServico = new javax.swing.JTextField();
        txtProdutos = new javax.swing.JTextField();
        btnBuscarServ = new javax.swing.JButton();
        btnBuscarProd = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServ = new javax.swing.JTable();
        btnAddProd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProd = new javax.swing.JTable();
        btnAddServ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cliente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 64, -1, -1));

        txtNomeCliente.setEditable(false);
        jPanel1.add(txtNomeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 103, 310, 37));

        btnBuscarCliente.setFont(new java.awt.Font("Courier New", 2, 14)); // NOI18N
        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarClienteMouseClicked(evt);
            }
        });
        jPanel1.add(btnBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 86, 40));

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cadastro de Atendimento");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 18, -1, -1));

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Animal");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        txtAnimal.setEditable(false);
        txtAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnimalActionPerformed(evt);
            }
        });
        jPanel1.add(txtAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 302, 40));

        btnBuscarAnimal.setFont(new java.awt.Font("Courier New", 2, 14)); // NOI18N
        btnBuscarAnimal.setText("Buscar");
        btnBuscarAnimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarAnimalMouseClicked(evt);
            }
        });
        btnBuscarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAnimalActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 87, 42));

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Serviço");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Produtos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        txtServico.setEditable(false);
        txtServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServicoActionPerformed(evt);
            }
        });
        jPanel1.add(txtServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 302, 39));

        txtProdutos.setEditable(false);
        txtProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdutosActionPerformed(evt);
            }
        });
        jPanel1.add(txtProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 302, 41));

        btnBuscarServ.setFont(new java.awt.Font("Courier New", 2, 14)); // NOI18N
        btnBuscarServ.setText("Buscar");
        btnBuscarServ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarServMouseClicked(evt);
            }
        });
        btnBuscarServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarServActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 87, 39));

        btnBuscarProd.setFont(new java.awt.Font("Courier New", 2, 14)); // NOI18N
        btnBuscarProd.setText("Buscar");
        btnBuscarProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarProdMouseClicked(evt);
            }
        });
        btnBuscarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 87, 41));

        jButton4.setFont(new java.awt.Font("Courier New", 2, 14)); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 100, 40));

        btnSalvar.setFont(new java.awt.Font("Courier New", 2, 14)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, 80, 40));

        tblServ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descrição", "Preço", "Tempo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblServ);
        if (tblServ.getColumnModel().getColumnCount() > 0) {
            tblServ.getColumnModel().getColumn(0).setResizable(false);
            tblServ.getColumnModel().getColumn(1).setResizable(false);
            tblServ.getColumnModel().getColumn(2).setResizable(false);
            tblServ.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 430, 160));

        btnAddProd.setFont(new java.awt.Font("Courier New", 2, 14)); // NOI18N
        btnAddProd.setText("Adicionar");
        btnAddProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddProdMouseClicked(evt);
            }
        });
        btnAddProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProdActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, -1, 40));

        tblProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descriçao", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblProd);
        if (tblProd.getColumnModel().getColumnCount() > 0) {
            tblProd.getColumnModel().getColumn(0).setResizable(false);
            tblProd.getColumnModel().getColumn(1).setResizable(false);
            tblProd.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 430, 160));

        btnAddServ.setFont(new java.awt.Font("Courier New", 2, 14)); // NOI18N
        btnAddServ.setText("Adicionar");
        btnAddServ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddServMouseClicked(evt);
            }
        });
        btnAddServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddServActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1042, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarClienteMouseClicked
        //Crio a tela de consulta de cliente
        FrConsultCliente telaConsultar = new FrConsultCliente(null, rootPaneCheckingEnabled);
        telaConsultar.setVisible(true);

        //Quando fechar a tela de consultar vai voltar aqui e testar se selecionou ou não
        if (!telaConsultar.getNome().equals("")) {
            txtNomeCliente.setText(telaConsultar.getNome());
            idCliente = telaConsultar.getId();
        } else {
            JOptionPane.showMessageDialog(this, "Não foi selecionado um cliente");
        }
    }//GEN-LAST:event_btnBuscarClienteMouseClicked

    private void btnBuscarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarAnimalActionPerformed

    private void txtAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnimalActionPerformed

    private void txtServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServicoActionPerformed

    private void txtProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdutosActionPerformed

    private void btnBuscarServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarServActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarServActionPerformed

    private void btnBuscarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarProdActionPerformed

    private void btnBuscarAnimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarAnimalMouseClicked
        frConsultarAnimal telaConsultar = new frConsultarAnimal(null, rootPaneCheckingEnabled);
        telaConsultar.setVisible(true);

        //Quando fechar a tela de consultar vai voltar aqui e testar se selecionou ou não
        if (!telaConsultar.getNome().equals("")) {
            txtAnimal.setText(telaConsultar.getNome());
            idAnimal = telaConsultar.getId();

        } else {
            JOptionPane.showMessageDialog(this, "Não foi selecionado um Animal !");
        }

    }//GEN-LAST:event_btnBuscarAnimalMouseClicked

    private void btnBuscarServMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarServMouseClicked
        FrConsultServico telaConsultar = new FrConsultServico(null, rootPaneCheckingEnabled);
        telaConsultar.setVisible(true);

        //Quando fechar a tela de consultar vai voltar aqui e testar se selecionou ou não
        if (!telaConsultar.getDesc().equals("")) {
            txtServico.setText(telaConsultar.getDesc());
            idServico = telaConsultar.getId();
            precoServ = telaConsultar.getPreco();
            tempo = telaConsultar.getTempo();
        } else {
            JOptionPane.showMessageDialog(this, "Não foi selecionado um Serviço !");
        }

    }//GEN-LAST:event_btnBuscarServMouseClicked

    private void btnBuscarProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarProdMouseClicked
        // TODO add your handling code here:
        FrConsultProduto telaConsultar = new FrConsultProduto(null, rootPaneCheckingEnabled);
        telaConsultar.setVisible(true);

        //Quando fechar a tela de consultar vai voltar aqui e testar se selecionou ou não
        if (!telaConsultar.getDesc().equals("")) {
            txtProdutos.setText(telaConsultar.getDesc());
            idProduto = telaConsultar.getId();
            precoProd = telaConsultar.getPreco();
        } else {
            JOptionPane.showMessageDialog(this, "Não foi selecionado um Produto !");
        }

    }//GEN-LAST:event_btnBuscarProdMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        gravar();

    }//GEN-LAST:event_btnSalvarMouseClicked

    private void btnAddProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddProdActionPerformed

    private void btnAddServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddServActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddServActionPerformed

    private void btnAddServMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddServMouseClicked
        DefaultTableModel modelotabela = (DefaultTableModel) tblServ.getModel();

        Object[] linha = {
            idServico,
            txtServico.getText(),
            precoServ,
            tempo
        };
        modelotabela.addRow(linha);
        txtServico.setText("");

    }//GEN-LAST:event_btnAddServMouseClicked

    private void btnAddProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProdMouseClicked
        DefaultTableModel modelotabela = (DefaultTableModel) tblProd.getModel();

        Object[] linha = {
            idProduto,
            txtProdutos.getText(),
            precoProd
        };
        modelotabela.addRow(linha);
        txtProdutos.setText("");
    }//GEN-LAST:event_btnAddProdMouseClicked
    public void gravar() {
        Atendimentos atend = new Atendimentos();
        atend.setFkcliente(idCliente);
        atend.setFkanimal(idAnimal);

        AtendimentosController controller = new AtendimentosController();
        controller.inserirAtendimento(atend);
        int pkAtendimento = controller.consultarUltimo();
        gravarAtendProd(pkAtendimento);
        gravarAtendServ(pkAtendimento);
    }

    public void gravarAtendProd(int pkAtendimento) {
        
        for (int i = 0; i < tblProd.getRowCount(); i++) {
            AtendimentoProd prod = new AtendimentoProd();
            AtendimentosController controller = new AtendimentosController();
            prod.setFkAtendimento(pkAtendimento);
            int textoId = Integer.parseInt(tblProd.getValueAt(i, 0).toString());
            prod.setFkProd(textoId);
            controller.inserirAtendimentoProd(prod);
        }
    }

    public void gravarAtendServ(int pkAtendimento) {
        for (int i = 0; i < tblServ.getRowCount(); i++) {
            AtendimentoServ serv = new AtendimentoServ();
            AtendimentosController c = new AtendimentosController();
            
            serv.setFkAtendimento(pkAtendimento);
            
            int textoId =  Integer.parseInt(tblServ.getValueAt(i, 0).toString());
            serv.setFkServico(textoId);
            c.inserirAtendimentoServicos(serv);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrCadAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrCadAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrCadAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCadAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrCadAtendimento dialog = new FrCadAtendimento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProd;
    private javax.swing.JButton btnAddServ;
    private javax.swing.JButton btnBuscarAnimal;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarProd;
    private javax.swing.JButton btnBuscarServ;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblProd;
    private javax.swing.JTable tblServ;
    private javax.swing.JTextField txtAnimal;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtProdutos;
    private javax.swing.JTextField txtServico;
    // End of variables declaration//GEN-END:variables
}
