/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AtendimentosController;
import controller.FuncionariosController;
import javax.swing.JOptionPane;
import model.Atendimentos;
import model.Funcionario;

/**
 *
 * @author suezin
 */
public class FrCadAtendimento extends javax.swing.JDialog {

    /**
     * Creates new form FrCadAtendimento
     */
    public FrCadAtendimento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAnimal = new javax.swing.JTextField();
        btnBuscarAnimal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtServico = new javax.swing.JTextField();
        txtProdutos = new javax.swing.JTextField();
        btnBuscarServ = new javax.swing.JButton();
        btnBuscarProd = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cliente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 64, -1, -1));
        jPanel1.add(txtNomeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 103, 310, 37));

        btnBuscarCliente.setFont(new java.awt.Font("Courier New", 2, 14)); // NOI18N
        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarClienteMouseClicked(evt);
            }
        });
        jPanel1.add(btnBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 86, 40));

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cadastro de Atendimento");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 18, -1, -1));

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Animal");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        txtAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnimalActionPerformed(evt);
            }
        });
        jPanel1.add(txtAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 302, 40));

        btnBuscarAnimal.setFont(new java.awt.Font("Courier New", 2, 14)); // NOI18N
        btnBuscarAnimal.setText("Buscar");
        btnBuscarAnimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarAnimalMouseClicked(evt);
            }
        });
        btnBuscarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAnimalActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 87, 42));

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Serviço");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Produtos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        txtServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServicoActionPerformed(evt);
            }
        });
        jPanel1.add(txtServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 302, 39));

        txtProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdutosActionPerformed(evt);
            }
        });
        jPanel1.add(txtProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 302, 41));

        btnBuscarServ.setFont(new java.awt.Font("Courier New", 2, 14)); // NOI18N
        btnBuscarServ.setText("Buscar");
        btnBuscarServ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarServMouseClicked(evt);
            }
        });
        btnBuscarServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarServActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 87, 39));

        btnBuscarProd.setFont(new java.awt.Font("Courier New", 2, 14)); // NOI18N
        btnBuscarProd.setText("Buscar");
        btnBuscarProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarProdMouseClicked(evt);
            }
        });
        btnBuscarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 87, 41));

        jButton4.setFont(new java.awt.Font("Courier New", 2, 14)); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 100, 40));

        btnSalvar.setFont(new java.awt.Font("Courier New", 2, 14)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, 80, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarClienteMouseClicked
        //Crio a tela de consulta de cliente
        FrConsultCliente telaConsultar = new FrConsultCliente(null, rootPaneCheckingEnabled);
        telaConsultar.setVisible(true);

        //Quando fechar a tela de consultar vai voltar aqui e testar se selecionou ou não
        if(!telaConsultar.getNome().equals("")){
            txtNomeCliente.setText(telaConsultar.getNome());
        }else{
            JOptionPane.showMessageDialog(this, "Não foi selecionado um cliente");
        }
    }//GEN-LAST:event_btnBuscarClienteMouseClicked

    private void btnBuscarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarAnimalActionPerformed

    private void txtAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnimalActionPerformed

    private void txtServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServicoActionPerformed

    private void txtProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdutosActionPerformed

    private void btnBuscarServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarServActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarServActionPerformed

    private void btnBuscarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarProdActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnBuscarAnimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarAnimalMouseClicked
        frConsultarAnimal telaConsultar = new frConsultarAnimal(null, rootPaneCheckingEnabled);
        telaConsultar.setVisible(true);

        //Quando fechar a tela de consultar vai voltar aqui e testar se selecionou ou não
        if(!telaConsultar.getNome().equals("")){
            txtAnimal.setText(telaConsultar.getNome());
        }else{
            JOptionPane.showMessageDialog(this, "Não foi selecionado um Animal !");
        }
        
    }//GEN-LAST:event_btnBuscarAnimalMouseClicked

    private void btnBuscarServMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarServMouseClicked
        FrConsultServico telaConsultar = new FrConsultServico(null, rootPaneCheckingEnabled);
        telaConsultar.setVisible(true);

        //Quando fechar a tela de consultar vai voltar aqui e testar se selecionou ou não
        if(!telaConsultar.getDesc().equals("")){
            txtServico.setText(telaConsultar.getDesc());
        }else{
            JOptionPane.showMessageDialog(this, "Não foi selecionado um Serviço !");
        }
        
    }//GEN-LAST:event_btnBuscarServMouseClicked

    private void btnBuscarProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarProdMouseClicked
        // TODO add your handling code here:
        FrConsultProduto telaConsultar = new FrConsultProduto(null, rootPaneCheckingEnabled);
        telaConsultar.setVisible(true);

        //Quando fechar a tela de consultar vai voltar aqui e testar se selecionou ou não
        if(!telaConsultar.getDesc().equals("")){
            txtProdutos.setText(telaConsultar.getDesc());
        }else{
            JOptionPane.showMessageDialog(this, "Não foi selecionado um Produto !");
        }
        
    }//GEN-LAST:event_btnBuscarProdMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
gravar();
gravarAtendProd();
gravarAtendServ();
    }//GEN-LAST:event_btnSalvarMouseClicked
 public void gravar() {
        FrConsultCliente telaConsultarCliente = new FrConsultCliente(null, rootPaneCheckingEnabled);
        frConsultarAnimal telaConsultarAnimal = new frConsultarAnimal(null, rootPaneCheckingEnabled);
        Atendimentos atend = new Atendimentos();
        atend.setFkcliente(telaConsultarCliente.getId());
        atend.setFkanimal(telaConsultarAnimal.getId());

         AtendimentosController controller = new AtendimentosController();
        controller.inserirAtendimento(atend);

    }
 
 public void gravarAtendProd() {
        FrConsultProduto telaConsultarProd = new FrConsultProduto(null, rootPaneCheckingEnabled);
         AtendimentosController controller = new AtendimentosController();
        Atendimentos atend = new Atendimentos();
        atend.setFkproduto(telaConsultarProd.getId());
        atend.setFkatendimento(controller.consultar());

        
        controller.inserirAtendimento(atend);

    }
 
 public void gravarAtendServ() {
        FrConsultServico telaConsultarServ = new FrConsultServico(null, rootPaneCheckingEnabled);
         AtendimentosController controller = new AtendimentosController();
        Atendimentos atend = new Atendimentos();
        atend.setFkservico(telaConsultarServ.getId());
        atend.setFkatendimento(controller.consultar());

        
        controller.inserirAtendimento(atend);

    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrCadAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrCadAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrCadAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCadAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrCadAtendimento dialog = new FrCadAtendimento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAnimal;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarProd;
    private javax.swing.JButton btnBuscarServ;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAnimal;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtProdutos;
    private javax.swing.JTextField txtServico;
    // End of variables declaration//GEN-END:variables
}
